# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: insights-secret
  namespace: cloudcrafter
type: Opaque
data:
  # Example:
  # password: {{ .Values.password | b64enc }}
  github-client-id: SXYyM2xpQ0JNbXF0OGpMT2VYcFEK
  github-client-secret: NTliZDVlYTVlZTFlYjM4ZGQyODlmMDIxNzM2MzQ0ZDlhOGM3NDQwNgo= 
---

